export const CMS_LIMITS = {
  maxCollectionsPerWebsite: 40,
  maxFieldsPerCollection: 40,
  maxRecordsPerCollection: 5000,
  maxRevisionsKept: 20,
  maxTextChars: 5000,
  maxRecordJsonBytes: 200_000,
  maxReferences: 50,
  maxFilters: 10,
  maxPageSize: 100,
  defaultPageSize: 20,
  publicMaxPageSize: 50,
  publicDefaultLimit: 50,
} as const;

export const RESERVED_CMS_SLUGS = new Set([
  'api',
  'admin',
  'login',
  'logout',
  'signup',
  'register',
  'media',
  'documents',
  'websites',
  'public',
  'cms',
  'site',
  'assets',
  'static',
  'health',
  'docs',
  'auth',
  'dashboard',
  'billing',
  'checkout',
  'null',
  'undefined',
]);
